apiVersion: apps/v1
kind: Deployment
metadata:
    name: cygnusservice
    namespace: scheduled
    labels:
        app: cygnus
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cygnus
    template:
        metadata:
            labels:
                app: cygnus
        spec:
            containers:
            - name: fiware-cygnus
              image: fiware/cygnus-ngsi:latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 5080
                - containerPort: 5051
              env:
                - name: CYGNUS_MONGO_HOSTS
                  valueFrom:
                    secretKeyRef: 
                        name: cygnus-secret
                        key: mongo_hosts
                - name: CYGNUS_LOG_LEVEL
                  valueFrom:
                    secretKeyRef: 
                        name: cygnus-secret
                        key: log_level
                - name: CYGNUS_SERVICE_PORT
                  valueFrom:
                    secretKeyRef: 
                        name: cygnus-secret
                        key: service_port
                - name: CYGNUS_API_PORT
                  valueFrom:
                    secretKeyRef: 
                        name: cygnus-secret
                        key: api_port
              resources:
                requests:
                  cpu: 10m
                  memory: 250Mi
                limits:
                  cpu: 200m
                  memory: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cygnusserviceproxy
    namespace: scheduled
    labels:
        app: cygnusproxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cygnusproxy
    template:
        metadata:
            labels:
                app: cygnusproxy
        spec:
            containers:
                - name: cygnus-proxy
                  image: fiware/pep-proxy:7.5.0
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 5052
                      protocol: TCP
                  env:
                    - name: PEP_PROXY_APP_HOST
                      valueFrom:
                        secretKeyRef: 
                            name: cygnusproxy-secret
                            key: app_host
                    - name: PEP_PROXY_APP_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: app_port
                    - name: PEP_PROXY_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: port
                    - name: PEP_PROXY_IDM_HOST
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: idm_host
                    - name: PEP_PROXY_HTTPS_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: https_enables
                    - name: PEP_PROXY_AUTH_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: auth_enabled
                    - name: PEP_PROXY_IDM_SSL_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: idm_ssl_enabled
                    - name: PEP_PROXY_IDM_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: idm_port
                    - name: PEP_PROXY_APP_ID
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: app_id
                    - name: PEP_PROXY_USERNAME
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: username
                    - name: PEP_PASSWORD
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: password
                    - name: PEP_PROXY_PDP
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: pdp_host
                    - name: PEP_PROXY_MAGIC_KEY
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: magic_key
                    - name: PEP_PROXY_AZF_PROTOCOL
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: azf_protocol
                    - name: PEP_PROXY_AZF_HOST
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: azf_host
                    - name: PEP_PROXY_AZF_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: cygnusproxy-secret
                          key: azf_port
                  resources:
                    requests:
                      cpu: 10m
                      memory: 100Mi
                    limits:
                      cpu: 100m
                      memory: 200Mi
