apiVersion: apps/v1
kind: Deployment
metadata:
    name: orionservice
    namespace: scheduled
    labels:
        app: orion
spec:
    replicas: 1
    selector:
        matchLabels:
            app: orion
    template:
        metadata:
            labels:
                app: orion
        spec:
            containers:
              - name: orion
                image: fiware/orion:latest
                imagePullPolicy: IfNotPresent
                ports:
                 - containerPort: 1026
                args: ["-dbhost", "mongoservice:27017", "-logLevel", "INFO"]
                resources:
                  requests:
                    cpu: 10m
                    memory: 50Mi
                  limits:
                    cpu: 200m
                    memory: 200Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: orionserviceproxy
    namespace: scheduled
    labels:
        app: orionproxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: orionproxy
    template:
        metadata:
            labels:
                app: orionproxy
        spec:
            containers:
                - name: orion-propxy
                  image: fiware/pep-proxy:7.5.0
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 1027
                      protocol: TCP
                  env:
                    - name: PEP_PROXY_APP_HOST
                      valueFrom:
                        secretKeyRef: 
                            name: orionproxy-secret
                            key: app_host
                    - name: PEP_PROXY_APP_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: app_port
                    - name: PEP_PROXY_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: port
                    - name: PEP_PROXY_IDM_HOST
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: idm_host
                    - name: PEP_PROXY_HTTPS_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: https_enables
                    - name: PEP_PROXY_AUTH_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: auth_enabled
                    - name: PEP_PROXY_IDM_SSL_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: idm_ssl_enabled
                    - name: PEP_PROXY_IDM_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: idm_port
                    - name: PEP_PROXY_APP_ID
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: app_id
                    - name: PEP_PROXY_USERNAME
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: username
                    - name: PEP_PASSWORD
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: password
                    - name: PEP_PROXY_PDP
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: pdp_host
                    - name: PEP_PROXY_MAGIC_KEY
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: magic_key
                    - name: PEP_PROXY_AZF_PROTOCOL
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: azf_protocol
                    - name: PEP_PROXY_AZF_HOST
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: azf_host
                    - name: PEP_PROXY_AZF_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: orionproxy-secret
                          key: azf_port
                  resources:
                    requests:
                      cpu: 10m
                      memory: 100Mi
                    limits:
                      cpu: 100m
                      memory: 200Mi
