apiVersion: apps/v1
kind: Deployment
metadata:
    name: queryingsensorsservice
    namespace: scheduled
    labels:
        app: queryingsensors
spec:
    replicas: 1
    selector:
        matchLabels:
            app: queryingsensors
    template:
        metadata:
            labels:
                app: queryingsensors
        spec:
            containers:
              - name: queryingsensors
                image: ktsakos/ixenfinal_querying-sensors:latest
                imagePullPolicy: IfNotPresent
                ports:
                 - containerPort: 1024
                resources:
                  requests:
                    cpu: 10m
                    memory: 50Mi
                  limits:
                    cpu: 200m
                    memory: 200Mi
                volumeMounts: 
                   - mountPath: /usr/src/app
                     name: queryingsensors-volume

            volumes:
                - name: queryingsensors-volume
                  persistentVolumeClaim:
                    claimName: queryingsensors-volume-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: queryingsensorsserviceproxy
    namespace: scheduled
    labels:
        app: queryingsensorsproxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: queryingsensorsproxy
    template:
        metadata:
            labels:
                app: queryingsensorsproxy
        spec:
            containers:
                - name: queryingsensors-proxy
                  image: fiware/pep-proxy:7.5.0
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 1025
                      protocol: TCP
                  env:
                    - name: PEP_PROXY_APP_HOST
                      valueFrom:
                        secretKeyRef: 
                            name: queryingsensorsproxy-secret
                            key: app_host
                    - name: PEP_PROXY_APP_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: app_port
                    - name: PEP_PROXY_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: port
                    - name: PEP_PROXY_IDM_HOST
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: idm_host
                    - name: PEP_PROXY_HTTPS_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: https_enables
                    - name: PEP_PROXY_AUTH_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: auth_enabled
                    - name: PEP_PROXY_IDM_SSL_ENABLED
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: idm_ssl_enabled
                    - name: PEP_PROXY_IDM_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: idm_port
                    - name: PEP_PROXY_APP_ID
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: app_id
                    - name: PEP_PROXY_USERNAME
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: username
                    - name: PEP_PASSWORD
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: password
                    - name: PEP_PROXY_PDP
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: pdp_host
                    - name: PEP_PROXY_MAGIC_KEY
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: magic_key
                    - name: PEP_PROXY_AZF_PROTOCOL
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: azf_protocol
                    - name: PEP_PROXY_AZF_HOST
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: azf_host
                    - name: PEP_PROXY_AZF_PORT
                      valueFrom:
                        secretKeyRef: 
                          name: queryingsensorsproxy-secret
                          key: azf_port
                  resources:
                    requests:
                      cpu: 10m
                      memory: 100Mi
                    limits:
                      cpu: 100m
                      memory: 200Mi
