apiVersion: v1
kind: Service
metadata:
  name: authzforceservice
  namespace: scheduled
spec:
  selector:
    app: authzforce
  clusterIP: 10.48.0.4
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080