apiVersion: v1
kind: Service
metadata:
  name: noderedservice
  namespace: scheduled
spec:
  selector:
    app: nodered
  clusterIP: 10.48.0.5
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: noderedserviceproxy
  namespace: scheduled
spec:
  selector:
    app: noderedproxy
  clusterIP: 10.48.0.6
  ports:
  - protocol: TCP
    port: 1881
    targetPort: 1881